### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by BliXem1** [teamsuperpanda/Weather-Station#1]
Hi,

Thanks for this project! Can we see your data live (via ESPhome?) :)

I'm thinking to buy the V4 weather station, but first want to see the data in the summer. Is the temperature accurate?

**Comment by teamsuperpanda** [comment]
Hi there,

When it comes to accuracy, it largely depends on the sensors you're using. I currently have both the BME280 and an external Dallas temperature sensor in my setup. Their readings can be quite similar, but if the enclosure gets warm, there might be a difference of a degree or two. Personally, I don't rely much on the BME280 for temperature.

As for the Dallas sensor, I had a funny experience with it initially—I had it positioned in direct sunlight! As a result, the morning readings were way off, with temperatures like 27°C, which isn’t typical for mornings in New Zealand. The fix was simple: I moved it behind the wooden mount for shade, and now it’s spot-on. I even cross-referenced its readings with local weather data, and they align perfectly.

One feature I'm looking to add is dynamic deep sleep. My current setup deep-sleeps every 15 minutes, but I’m considering waking it up every hour overnight and increasing activity during the day.

![Screenshot 2024-11-26 110011](https://github.com/user-attachments/assets/78db13ff-341d-44cd-a1cf-ef4c29018d1d)

**Comment by BliXem1** [comment]
Hi,

Maybe you can try BMP390? It's more accurate they say.

Looks good, thanks! I will buy the 390 first and add it in a 3d printed steverson screen.
